#include "tilemap.h"
#include "SDL_rect.h"
#include "SDL_render.h"

int *IsTileBlocking(int tile) {
  int *blocking = (int *)malloc(sizeof(int) * 4);

  switch (tile) {
  case TILE_WALL_TOP:
    return blocking = (int[]){1, 0, 0, 0};
  case TILE_WALL_RIGHT:
    return blocking = (int[]){0, 1, 0, 0};
  case TILE_WALL_LEFT:
    return blocking = (int[]){0, 0, 0, 1};
  case TILE_WALL_BOTTOM:
    return blocking = (int[]){0, 0, 1, 0};
  case TILE_WALL_TOP_LEFT:
    return blocking = (int[]){1, 0, 0, 1};
  case TILE_WALL_TOP_RIGHT:
    return blocking = (int[]){1, 1, 0, 0};
  case TILE_WALL_BOTTOM_LEFT:
    return blocking = (int[]){0, 0, 1, 1};
  case TILE_WALL_BOTTOM_RIGHT:
    return blocking = (int[]){0, 1, 1, 0};
  default:
    return NULL;
  }
}

SDL_Rect GetTileRect(int tileIndex) {
  SDL_Rect rect;
  int row = tileIndex / MAX_TILES_X;
  int col = tileIndex % MAX_TILES_X;

  rect.x = col * TILE_SIZE;
  rect.y = row * TILE_SIZE;
  rect.w = TILE_SIZE;
  rect.h = TILE_SIZE;
  return rect;
}

void DrawTile(SDL_Texture *tiles, SDL_Renderer *renderer, int tile, int x,
              int y) {
  if (tile == TILE_EMPTY) {
    return;
  }

  SDL_Rect srcRect = GetTileRect(tile);
  SDL_Rect dstRect = {x, y, TILE_SIZE, TILE_SIZE};

  switch (tile) {
  case TILE_WALL_RIGHT:
  case TILE_WALL_TOP_LEFT:
  case TILE_WALL_TOP_RIGHT:
  case TILE_WALL_BOTTOM_LEFT:
  case TILE_WALL_BOTTOM_RIGHT:
  case TILE_WALL_LEFT: {
    SDL_Rect floorRect = GetTileRect(TILE_FLOOR);
    SDL_RenderCopy(renderer, tiles, &floorRect, &dstRect);
    break;
  }
  default: {
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
    SDL_RenderFillRect(renderer, &dstRect);
    break;
  }
  }

  SDL_RenderCopy(renderer, tiles, &srcRect, &dstRect);
}

int mapData[MAP_HEIGHT][MAP_WIDTH] = {
    {TILE_WALL_TOP_LEFT, TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_BOTTOM_LEFT, TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM_RIGHT},
};
