#include "tilemap.h"
#include "SDL_image.h"
#include "SDL_rect.h"
#include "SDL_render.h"
#include "vector.h"
#include "window.h"

static SDL_Texture *tiles = NULL;

int *IsTileBlocking(int tile) {
  int *blocking = (int *)malloc(sizeof(int) * 4);

  switch (tile) {
  case TILE_WALL_TOP:
    return blocking = (int[]){1, 0, 0, 0};
  case TILE_WALL_RIGHT:
    return blocking = (int[]){0, 1, 0, 0};
  case TILE_WALL_LEFT:
    return blocking = (int[]){0, 0, 0, 1};
  case TILE_WALL_BOTTOM:
    return blocking = (int[]){0, 0, 1, 0};
  case TILE_WALL_TOP_LEFT:
    return blocking = (int[]){1, 0, 0, 1};
  case TILE_WALL_TOP_RIGHT:
    return blocking = (int[]){1, 1, 0, 0};
  case TILE_WALL_BOTTOM_LEFT:
    return blocking = (int[]){0, 0, 1, 1};
  case TILE_WALL_BOTTOM_RIGHT:
    return blocking = (int[]){0, 1, 1, 0};
  default:
    return NULL;
  }
}

SDL_Rect GetTileRect(int tileIndex) {
  SDL_Rect rect;
  int row = tileIndex / MAX_TILES_X;
  int col = tileIndex % MAX_TILES_X;

  rect.x = col * TILE_SIZE;
  rect.y = row * TILE_SIZE;
  rect.w = TILE_SIZE;
  rect.h = TILE_SIZE;
  return rect;
}

static void DrawTile(SDL_Texture *tiles, SDL_Renderer *renderer, int tile,
                     int x, int y) {
  if (tile == TILE_EMPTY) {
    return;
  }

  SDL_Rect srcRect = GetTileRect(tile);
  SDL_Rect dstRect = {x, y, TILE_SIZE, TILE_SIZE};

  switch (tile) {
  case TILE_WALL_RIGHT:
  case TILE_WALL_TOP_LEFT:
  case TILE_WALL_TOP_RIGHT:
  case TILE_WALL_BOTTOM_LEFT:
  case TILE_WALL_BOTTOM_RIGHT:
  case TILE_WALL_LEFT: {
    SDL_Rect floorRect = GetTileRect(TILE_FLOOR);
    SDL_RenderCopy(renderer, tiles, &floorRect, &dstRect);
    break;
  }
  default: {
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
    SDL_RenderFillRect(renderer, &dstRect);
    break;
  }
  }

  SDL_RenderCopy(renderer, tiles, &srcRect, &dstRect);
}

int mapData[MAP_HEIGHT][MAP_WIDTH] = {
    {TILE_WALL_TOP_LEFT, TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP,      TILE_WALL_TOP, TILE_WALL_TOP, TILE_WALL_TOP,
     TILE_WALL_TOP_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_LEFT, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_FLOOR,
     TILE_FLOOR,     TILE_FLOOR, TILE_FLOOR, TILE_FLOOR, TILE_WALL_RIGHT},
    {TILE_WALL_BOTTOM_LEFT, TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM,      TILE_WALL_BOTTOM, TILE_WALL_BOTTOM,
     TILE_WALL_BOTTOM_RIGHT},
};

void InitTilemap(SDL_Renderer *ren, SDL_Window *win) {
  SDL_Surface *tileSurface = IMG_Load("./assets/tech/tileset x1.png");
  if (!tileSurface) {
    SDL_Log("IMG_Load Error: %s\n", IMG_GetError());
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    IMG_Quit();
    SDL_Quit();
    exit(1);
  }
  tiles = SDL_CreateTextureFromSurface(ren, tileSurface);
  SDL_FreeSurface(tileSurface);
}

void DrawTilemap(SDL_Renderer *ren) {
  Vector2 camera = GetCameraPosition();

  for (int row = 0; row < MAP_HEIGHT; row++) {
    for (int col = 0; col < MAP_WIDTH; col++) {
      int tile = mapData[row][col];
      int posX = (col * TILE_SIZE) - (int)camera.x;
      int posY = (row * TILE_SIZE) - (int)camera.y;
      DrawTile(tiles, ren, tile, posX, posY);
    }
  }
}

void DestroyTilemap() { SDL_DestroyTexture(tiles); }
